### PR TITLE
Release 3.0.2

### PR DESCRIPTION
**Pull request by iampelle**
- @jakorostami added docstring to Experiment class
- @joaomilho fix spelling error
- Added tornade version requirement to protect agains vulnerability

### CODE REVIEW

**Review by ankargren — APPROVED** [review]

**Comment by ankargren** [comment]
@iampelle do we need to update `setup.cfg` too with the new version?

**Comment by iampelle** [comment]
> @iampelle do we need to update `setup.cfg` too with the new version?

Yes! And also the history and readme files.

**Comment by iampelle** [comment]
What do you think about the description of your change in the History file @ankargren? Feel free to tweak it if you like.

**Comment by ankargren** [comment]
Sorry just saw this now @iampelle – but it looks good!

**Pull request merged**
