### PR TITLE
Fix default value for parameter level_as_reference - v2

### PR DESCRIPTION
**Pull request by ravimakhija**
## Summary

This PR is meant to replace PR #62 and address Issue #61. 

Per the discussion in PR #62, I set the default value of `level_as_reference` back to `None`, but kept the docstring edits. 

## Reference - Current Default Values

@iampelle I am actually not sure what the strategy for `level_as_reference` default values is (e.g. where to use True, False, or None), so I am leaving that out currently. Please feel free to take that over if it's easier (perhaps as a separate issue/PR), or else if more information is provided I'm happy to work on it further. 

Below are my findings for current default values. The file name is shown on the left, and default value on the right. Note that in some cases, the same file has different default values used in different places (e.g. in different methods). 

Here `False` is the default:

```
spotify_confidence/analysis/frequentist/experiment.py:        level_as_reference: bool = False,
spotify_confidence/analysis/bayesian/bayesian_models.py:    def multiple_difference(self, level, absolute=True, groupby=None, level_as_reference=False):
spotify_confidence/analysis/bayesian/bayesian_base.py:    def multiple_difference(self, level, absolute=True, groupby=None, level_as_reference=False):
spotify_confidence/analysis/bayesian/bayesian_base.py:    def multiple_difference_plot(self, level, absolute=True, groupby=None, level_as_reference=False):
```

And, here is where `True` is being used:

```
spotify_confidence/analysis/frequentist/confidence_computers/generic_computer.py:            level_as_reference=True,
spotify_confidence/analysis/frequentist/confidence_computers/generic_computer.py:            level_as_reference=True,
spotify_confidence/analysis/frequentist/confidence_computers/generic_computer.py:                level_as_reference=True,
```

And as discussed earlier, `None` is used here:

`spotify_confidence/analysis/frequentist/experiment.py:        level_as_reference: bool = None,`

### CODE REVIEW

**Comment by iampelle** [comment]
I seem to have missed the False default value in the [multiple_difference_plot method of the Experiment class](https://github.com/spotify/confidence/blob/master/spotify_confidence/analysis/frequentist/experiment.py#L236), that should be changed to `None` for consistency. It would be fantastic if you changed that in this PR as well.

[The cases](https://github.com/spotify/confidence/blob/master/spotify_confidence/analysis/frequentist/confidence_computers/generic_computer.py#L303) in `generic_computer`, where `True` is used in the call of `self._compute_differences(...)` isn't really a default value, and I think those cases are fine as is.

And I think we can leave the bayesian classes as is for now, not super important to change that right now in my oppinion.

**Comment by iampelle** [comment]
I changed the PR to point to the next release branch.

**Comment by ravimakhija** [comment]
Alright sounds good, thanks for the feedback! The last commit changes the default value to `None` for `multiple_different_plot`.

**Review by iampelle — APPROVED** [review]
Looks great, thanks for the effort!

**Pull request merged**
